INFO:apscheduler.scheduler:Scheduler started
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python310\lib\site-packages\telegram\ext\dispatcher.py", line 557, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python310\lib\site-packages\telegram\ext\handler.py", line 199, in handle_update
    return self.callback(update, context)
  File "C:\projects\mybot\bot.py", line 14, in greet_user
    print(1/0)
ZeroDivisionError: division by zero
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
WARNING:telegram.ext.updater:Exiting immediately!
